In [3]:
import numpy as np
arr1 = np.array([3,4,5,6,9])
arr2 = np.array([1,2,7,8,9])
print("Orignal arrays are:-")
print(arr1)
print(arr2)
print("Comparison-greater")
print(np.greater(arr1,arr2))
print("Comparison-greater_equal")
print(np.greater_equal(arr1,arr2))
print("Comparison-less")
print(np.less(arr1,arr2))
print("Comparison-less_equal")
print(np.less_equal(arr1,arr2))

Orignal arrays are:-
[3 4 5 6 9]
[1 2 7 8 9]
Comparison-greater
[ True  True False False False]
Comparison-greater_equal
[ True  True False False  True]
Comparison-less
[False False  True  True False]
Comparison-less_equal
[False False  True  True  True]


In [7]:
import numpy as np
print("An array of 10 zeros:")
print(np.zeros(10))
print("An array of 10 ones:")
print(np.ones(10))
print("An array of 10 fives:")
print(np.ones(10)*5)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
import numpy as np
x = np.array([[1,2],[5,6]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[1 2]
 [5 6]]
Sum of all elements:
14
Sum of each column:
[6 8]
Sum of each row:
[ 3 11]


In [12]:
import numpy as np
print("Add:")
print(np.add(3, 7))
print("Subtract:")
print(np.subtract(3,7))
print("Multiply:")
print(np.multiply(3, 7))
print("Divide:")
print(np.divide(3, 7))


Add:
10
Subtract:
-4
Multiply:
21
Divide:
0.42857142857142855


In [14]:
import numpy as np
print("sine: array of angles given in degrees")
print(np.sin(np.array((0, 30, 45, 60, 90)) * np.pi / 180))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0, 30, 45, 60, 90)) * np.pi / 180))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0, 30, 45, 60, 90)) * np.pi / 180))

sine: array of angles given in degrees
[0.         0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tangent: array of angles given in degrees
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [23]:
import pandas as pd
import numpy as np

goal_data  = {'Name': ['Rodrigo', 'Sadio', 'Kevin', 'Timo', 'Pierre', 'Jamie', 'Marcus', 'Harry', 'Callum', 'Wilfred'],
        'Country':['Spain','Senegal','Belgium','Germany','Gabon','England','England','England','England',' Ivory Coast'],
        'Goals': [10, 21, 16, 20, 22, 24, 14, 18, 6, 7],
        'Assists': [0, 9 ,14, 4, 5, 1, 4, 2, 1, 7],
        'Rating': [7, 9, 9, 8, 8.5 ,8 , 7.5 , 7.5, 6, 6.5 ]}
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Dframe = pd.DataFrame(goal_data , index=labels)
print(Dframe)

       Name       Country  Goals  Assists  Rating
1   Rodrigo         Spain     10        0     7.0
2     Sadio       Senegal     21        9     9.0
3     Kevin       Belgium     16       14     9.0
4      Timo       Germany     20        4     8.0
5    Pierre         Gabon     22        5     8.5
6     Jamie       England     24        1     8.0
7    Marcus       England     14        4     7.5
8     Harry       England     18        2     7.5
9    Callum       England      6        1     6.0
10  Wilfred   Ivory Coast      7        7     6.5


In [27]:
#selecting Name and Score
import pandas as pd
import numpy as np

goal_data  = {'Name': ['Rodrigo', 'Sadio', 'Kevin', 'Timo', 'Pierre', 'Jamie', 'Marcus', 'Harry', 'Callum', 'Wilfred'],
        'Country':['Spain','Senegal','Belgium','Germany','Gabon','England','England','England','England',' Ivory Coast'],
        'Goals': [10, 21, 16, 20, 22, 24, 14, 18, 6, 7],
        'Assists': [0, 9 ,14, 4, 5, 1, 4, 2, 1, 7],
        'Score': [7, 9, 9, 8, 8.5 ,8 , 7.5 , 7.5, 6, 6.5 ]}
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Dframe = pd.DataFrame(goal_data , index=labels)
print(Dframe)
print('Selecting Name and Score:')
print(Dframe[['Name','Score']])

       Name       Country  Goals  Assists  Score
1   Rodrigo         Spain     10        0    7.0
2     Sadio       Senegal     21        9    9.0
3     Kevin       Belgium     16       14    9.0
4      Timo       Germany     20        4    8.0
5    Pierre         Gabon     22        5    8.5
6     Jamie       England     24        1    8.0
7    Marcus       England     14        4    7.5
8     Harry       England     18        2    7.5
9    Callum       England      6        1    6.0
10  Wilfred   Ivory Coast      7        7    6.5
Selecting Name and Score:
       Name  Score
1   Rodrigo    7.0
2     Sadio    9.0
3     Kevin    9.0
4      Timo    8.0
5    Pierre    8.5
6     Jamie    8.0
7    Marcus    7.5
8     Harry    7.5
9    Callum    6.0
10  Wilfred    6.5


In [32]:
import pandas as pd

book_data1 = pd.DataFrame({
        'Book_id': ['B1', 'B2', 'B3', 'B4', 'B5'],
        'Name': ['Harry Potter', 'Lord Of The Rings', 'Maze Runner', 'Hunger Games', 'You'], 
        'Cost': [1000, 2010, 790, 1200, 699]})

book_data2 = pd.DataFrame({
        'Book_id': ['B6', 'B7', 'B8', 'B9', 'SB10'],
        'Name': ['ABC Murderers', 'Deep Work', 'Da Vinci Code', 'Divergent', 'Bring on the Noise'], 
        'Cost': [200, 250, 499, 1000, 500]})

print("Original DataFrames:")
print(book_data1)
print("____________________________________")
print(book_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([book_data1, book_data2])
print(result_data)

Original DataFrames:
  Book_id               Name  Cost
0      B1       Harry Potter  1000
1      B2  Lord Of The Rings  2010
2      B3        Maze Runner   790
3      B4       Hunger Games  1200
4      B5                You   699
____________________________________
  Book_id                Name  Cost
0      B6       ABC Murderers   200
1      B7           Deep Work   250
2      B8       Da Vinci Code   499
3      B9           Divergent  1000
4    SB10  Bring on the Noise   500

Join the said two dataframes along rows:
  Book_id                Name  Cost
0      B1        Harry Potter  1000
1      B2   Lord Of The Rings  2010
2      B3         Maze Runner   790
3      B4        Hunger Games  1200
4      B5                 You   699
0      B6       ABC Murderers   200
1      B7           Deep Work   250
2      B8       Da Vinci Code   499
3      B9           Divergent  1000
4    SB10  Bring on the Noise   500


In [41]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)
goal_data  = {'Name': ['Rodrigo', 'Sadio', 'Kevin', 'Timo', np.nan, 'Jamie', 'Marcus', 'Harry', np.nan, 'Wilfred'],
        'Country':['Spain',np.nan,'Belgium','Germany','Gabon','England','England',np.nan,'England',' Ivory Coast'],
        'Goals': [10, 21, 16, 20, 22, 24, 14, np.nan, 6, 7],
        'Assists': [0, 9 ,np.nan, 4, 5, 1, 4, 2, 1, 7],
        'Score': [np.nan, 9, 9, 8, 8.5 ,8 , 7.5 , 7.5, 6, 6.5 ]}
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Dframe = pd.DataFrame(goal_data , index=labels)
print(Dframe)
print("\nMissing values of the said dataframe:")
print(Dframe.isna())

       Name       Country  Goals  Assists  Score
1   Rodrigo         Spain   10.0      0.0    NaN
2     Sadio           NaN   21.0      9.0    9.0
3     Kevin       Belgium   16.0      NaN    9.0
4      Timo       Germany   20.0      4.0    8.0
5       NaN         Gabon   22.0      5.0    8.5
6     Jamie       England   24.0      1.0    8.0
7    Marcus       England   14.0      4.0    7.5
8     Harry           NaN    NaN      2.0    7.5
9       NaN       England    6.0      1.0    6.0
10  Wilfred   Ivory Coast    7.0      7.0    6.5

Missing values of the said dataframe:
     Name  Country  Goals  Assists  Score
1   False    False  False    False   True
2   False     True  False    False  False
3   False    False  False     True  False
4   False    False  False    False  False
5    True    False  False    False  False
6   False    False  False    False  False
7   False    False  False    False  False
8   False     True   True    False  False
9    True    False  False    False  False
10

In [45]:
import pandas as pd
ds = pd.Series([2, 3, 5, 7, 11, 13])
print(ds)


0     2
1     3
2     5
3     7
4    11
5    13
dtype: int64
